In [136]:
X = [[-1.1], [0.3], [0.5], [0.0], [0.1], [0.6], [100]]

# sklearn 异常值检测

## 孤立森林检测

In [137]:
from sklearn.ensemble import IsolationForest
iif_clf = IsolationForest()

In [138]:
iif_clf.fit(X)

IsolationForest()

In [139]:
y = [[0.1], [0], [90]]
iif_clf.predict(y)

array([ 1,  1, -1])

In [140]:
X_pre = iif_clf.predict(X)

In [141]:
X_pre = X_pre.reshape(7,1)

### -1为异常值

In [142]:
X_pre

array([[-1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1]])

In [143]:
import numpy as np
X = np.array(X)
X.shape

(7, 1)

### 评分

In [144]:
clf.decision_function(X)

ValueError: query data dimension must match training data dimension

In [ ]:
y=[[0.1], [0], [90]]
clf.decision_function(y)

array([ 0.1306367 ,  0.10098392, -0.25582572])

## OneClassSVM 方法

In [ ]:
from sklearn.svm import OneClassSVM
ocs_clf = OneClassSVM()

In [ ]:
ocs_clf.fit(X)
ocs_clf.predict(X)

array([-1,  1, -1,  1,  1, -1, -1], dtype=int64)

In [ ]:
ocs_clf.decision_function(X)

array([-1.31818638e-03,  1.46819921e-08, -4.63489812e-04,  3.89816309e-04,
        3.00621955e-04, -7.56298146e-04, -1.49797374e+00])

In [ ]:
ocs_clf.decision_function(y)

array([ 3.00621955e-04,  3.89816309e-04, -1.57390929e+00])

In [ ]:
ocs_clf.score_samples(X)

array([2.49734345, 2.49866165, 2.49819815, 2.49905145, 2.49896226,
       2.49790534, 1.0006879 ])

## LOF方法，无法predict

In [ ]:
from sklearn.neighbors import LocalOutlierFactor
lof = LocalOutlierFactor(n_neighbors=1)
lof.fit_predict(X)

array([-1, -1,  1,  1,  1,  1, -1])

In [ ]:
lof.negative_outlier_factor_

array([ -10.99999999,   -2.        ,   -1.        ,   -1.        ,
         -1.        ,   -1.        , -993.99999901])

##  EllipticEnvelope 椭圆法

In [ ]:
from sklearn.covariance import EllipticEnvelope
ee = EllipticEnvelope()
ee.fit_predict(X)

array([ 1,  1,  1,  1,  1,  1, -1])

In [ ]:
ee.predict(y)

array([ 1,  1, -1])

In [ ]:
ee.decision_function(X)

array([ 12657.43521127,  12661.57605634,  12661.15352113,  12661.73450704,
        12661.74507042,  12660.8471831 , -18986.1528169 ])

In [ ]:
ee.precision_

array([[3.16901408]])

# pyob包

![pyod算法比较](https://raw.githubusercontent.com/yzhao062/pyod/master/examples/ALL.png)

In [145]:
from pyod.models.knn import KNN
clf = KNN()
clf_name = 'KNN'
name = 'sb'
clf.fit(X)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [146]:
# 0为正常点，1为异常点
X_pred = clf.labels_

In [147]:
# 异常程度，返回值为原始分数。返回分数越高，则该数据点的异常程度越高
X_scores = clf.decision_scores_

In [148]:
clf.predict(y)

array([0, 0, 1])

In [149]:
clf.decision_function(y) 

array([ 0.5,  0.6, 89.9])

# 模型保存和加载
PyOD 在模型持久性方面采用了与 sklearn 类似的方法。有关说明，请参阅模型持久性。

简而言之，我们建议使用 joblib 或 pickle 来保存和加载 PyOD 模型。

In [150]:
from joblib import dump, load

# save the model
dump(clf, 'clf.joblib')
# load the model
clf = load('clf.joblib')

# 模型检测效果
采用ROC和 Precision@Rank n作为衡量标准。

**异常检测由于数据不平衡，一般不适用于准确度评估**

In [151]:
from pyod.utils.data import evaluate_print
# evaluate and print the results
print("\nOn Training Data:")
evaluate_print(name, X_pred, X_scores)
# 名字，真实标签，预测分数


On Training Data:
sb ROC:1.0, precision @ rank n:1.0

On Test Data:


In [152]:
from sklearn.metrics import roc_auc_score
roc_auc_score(X_pred,X_scores)

1.0