# XGBOOST调参

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [7]:
train = pd.read_csv('train.csv') 
test = pd.read_csv('test.csv')

D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3169: DtypeWarning: Columns (131) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


# 数据初步浏览

In [8]:
train.head()

id cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9  ...     cont7    cont8  \
0   1    A    B    A    B    A    A    A    A    B  ...  0.335060  0.30260   
1   2    A    B    A    A    A    A    A    A    B  ...  0.436585  0.60087   
2   5    A    B    A    A    B    A    A    A    B  ...  0.315545  0.27320   
3  10    B    B    A    B    A    A    A    A    B  ...  0.391128  0.31796   
4  11    A    B    A    B    A    A    A    A    B  ...  0.247408  0.24564   

     cont9   cont10    cont11    cont12    cont13    cont14     loss  \
0  0.67135  0.83510  0.569745  0.594646  0.822493  0.714843  2213.18   
1  0.35127  0.43919  0.338312  0.366307  0.611431  0.304496  1283.60   
2  0.26076  0.32446  0.381398  0.373424  0.195709  0.774425  3005.09   
3  0.32128  0.44467  0.327915  0.321570  0.605077  0.602642   939.85   
4  0.22089  0.21230  0.204687  0.202213  0.246011  0.432606  2763.85   

  Unnamed: 132  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  

[5 rows x 133 columns]

In [9]:
train.shape

(194592, 133)

In [20]:
train.info()
# 记得加括号

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194592 entries, 0 to 194591
Columns: 133 entries, id to Unnamed: 132
dtypes: float64(15), int64(1), object(117)
memory usage: 197.5+ MB


In [24]:
train['id'].dtypes

dtype('int64')

In [25]:
train.describe()

id          cont1          cont2          cont3  \
count  194592.000000  194592.000000  194592.000000  194592.000000   
mean   303280.484902       0.493792       0.507093       0.498875   
std    173957.482834       0.187636       0.207144       0.202033   
min         1.000000       0.000016       0.001149       0.002634   
25%    152556.750000       0.346090       0.358319       0.336963   
50%    304310.500000       0.475784       0.555782       0.527991   
75%    455284.250000       0.623912       0.681761       0.634224   
max    587633.000000       0.984975       0.862654       0.944251   

               cont4          cont5          cont6          cont7  \
count  194592.000000  194592.000000  194592.000000  194592.000000   
mean        0.491791       0.487384       0.490856       0.484889   
std         0.211273       0.208998       0.205329       0.178466   
min         0.176921       0.281143       0.012683       0.069503   
25%         0.327354       0.281143       0.335580       0.350175   
50%         0.452887       0.422268       0.440945       0.438285   
75%         0.652072       0.635304       0.654290       0.590807   
max         0.954297       0.983674       0.997162       1.000000   

               cont8          cont9         cont10         cont11  \
count  194592.000000  194592.000000  194592.000000  194592.000000   
mean        0.486468       0.485425       0.498049       0.493431   
std         0.199410       0.181634       0.185915       0.209739   
min         0.236880       0.000080       0.000000       0.035321   
25%         0.312800       0.358970       0.364580       0.310961   
50%         0.441060       0.437310       0.461190       0.457203   
75%         0.623580       0.566820       0.614590       0.678924   
max         0.980200       0.995400       0.994980       0.998742   

              cont12         cont13         cont14           loss  
count  194592.000000  194592.000000  194592.000000  194592.000000  
mean        0.493072       0.493112       0.495594    3036.251056  
std         0.209442       0.212785       0.222486    2900.977675  
min         0.036232       0.000228       0.179722       0.670000  
25%         0.308395       0.315758       0.294610    1204.262500  
50%         0.462286       0.363547       0.407325    2114.585000  
75%         0.675759       0.689974       0.724610    3862.492500  
max         0.998484       0.988494       0.844848  121012.250000

# 缺失值处理

In [31]:
# 是否存在缺失值
train.isnull().values.any()
# any()一个序列中满足一个True，则返回True；all()一个序列中所有值为True时，返回True，否则为False

True

In [30]:
# 统计缺失值数量
train.isnull().sum()

id                   0
cat1                 0
cat2                 0
cat3                 0
cat4                 0
                 ...  
cont12               0
cont13               0
cont14               0
loss                 0
Unnamed: 132    188318
Length: 133, dtype: int64

In [32]:
train_copy = train.copy(deep=True)

In [53]:
# 删除缺失值
train_copy = train_copy.dropna(axis=1)
train_copy.isnull().sum()

id        0
cat1      0
cat2      0
cat3      0
cat4      0
         ..
cont11    0
cont12    0
cont13    0
cont14    0
loss      0
Length: 132, dtype: int64

In [54]:
train_copy.isnull().values.any()

False

# 查看离散特征

In [55]:
train_copy.select_dtypes(include=['object'])
# select_dtypes返回具有指定数据类型的列

cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9 cat10  ... cat107 cat108  \
0         A    B    A    B    A    A    A    A    B     A  ...      J      G   
1         A    B    A    A    A    A    A    A    B     B  ...      K      K   
2         A    B    A    A    B    A    A    A    B     B  ...      F      A   
3         B    B    A    B    A    A    A    A    B     A  ...      K      K   
4         A    B    A    B    A    A    A    A    B     B  ...      G      B   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
194587    A    B    A    A    A    A    A    A    B     A  ...      G      B   
194588    A    A    A    A    A    B    A    A    A     A  ...      F      B   
194589    A    B    A    A    A    A    A    B    B     A  ...      F      B   
194590    A    B    A    A    A    A    A    A    B     B  ...      J      K   
194591    B    A    A    B    A    A    A    A    A     A  ...      G      G   

       cat109 cat110 cat111 cat112 cat113 cat114 cat115 cat116  
0          BU     BC      C     AS      S      A      O     LB  
1          BI     CQ      A     AV     BM      A      O     DP  
2          AB     DK      A      C     AF      A      I     GK  
3          BI     CS      C      N     AE      A      O     DJ  
4           H      C      C      Y     BM      A      K     CK  
...       ...    ...    ...    ...    ...    ...    ...    ...  
194587     BI     EG     A      G      BM      A      L     CK  
194588     BI     BT     A      AV     AU      E      J     DF  
194589     BI     DM     A      W      AF      A      K     DJ  
194590     BI     AI     A      AS     AJ      A      O     MD  
194591     BI     EG     K      AS     AD      A      O     MJ  

[194592 rows x 116 columns]

In [58]:
len(list(train_copy.select_dtypes(include=['float'])))

15

In [61]:
len(list(train_copy.select_dtypes(include=['int'])))

0

In [75]:
#scipy.stats 偏度
import scipy.stats as stats
stats.mstats.skew(train['loss'])

masked_array(data=3.76164014,
             mask=False,
       fill_value=1e+20)

In [68]:
stats.mstats.skew(np.log(train['loss'])).data

array(0.09292329)

In [76]:
# skew计算的是Fisher-Pearson 偏度系数
# skewtest计算的是正态分布的偏度
stats.mstats.skewtest(np.log(train['loss']))

SkewtestResult(statistic=16.69918272289433, pvalue=1.3287231279538517e-62)

In [77]:
import pandas as pd 
import numpy as np
import xgboost as xgb
import pickle
import sys
import matplotlib.pyplot as plt
from sklearn.metrics import make_scorer
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import LabelEncoder,LabelBinarizer
from sklearn.model_selection  import cross_val_score
from sklearn.model_selection import KFold,train_test_split

from xgboost import XGBRegressor

import warnings
warnings.filterwarnings('ignore')

In [81]:
train_copy['log_loss']=np.log(train_copy['loss'])
features = [x for x in train_copy.columns if x not in ['id','loss','log_loss']]
cat_features =[x for x in train_copy.select_dtypes(include = ['object']) if x not in ['id','loss','log_loss']]
num_features =[x for x in train_copy.select_dtypes(exclude = ['object']) if x not in ['id','loss','log_loss']]         
print('离散特征Categorical: {} features'.format(len(cat_features)))
print('Numerical:{} features'.format(len(num_features)))
features

离散特征Categorical: 116 features
Numerical:14 features


['cat1',
 'cat2',
 'cat3',
 'cat4',
 'cat5',
 'cat6',
 'cat7',
 'cat8',
 'cat9',
 'cat10',
 'cat11',
 'cat12',
 'cat13',
 'cat14',
 'cat15',
 'cat16',
 'cat17',
 'cat18',
 'cat19',
 'cat20',
 'cat21',
 'cat22',
 'cat23',
 'cat24',
 'cat25',
 'cat26',
 'cat27',
 'cat28',
 'cat29',
 'cat30',
 'cat31',
 'cat32',
 'cat33',
 'cat34',
 'cat35',
 'cat36',
 'cat37',
 'cat38',
 'cat39',
 'cat40',
 'cat41',
 'cat42',
 'cat43',
 'cat44',
 'cat45',
 'cat46',
 'cat47',
 'cat48',
 'cat49',
 'cat50',
 'cat51',
 'cat52',
 'cat53',
 'cat54',
 'cat55',
 'cat56',
 'cat57',
 'cat58',
 'cat59',
 'cat60',
 'cat61',
 'cat62',
 'cat63',
 'cat64',
 'cat65',
 'cat66',
 'cat67',
 'cat68',
 'cat69',
 'cat70',
 'cat71',
 'cat72',
 'cat73',
 'cat74',
 'cat75',
 'cat76',
 'cat77',
 'cat78',
 'cat79',
 'cat80',
 'cat81',
 'cat82',
 'cat83',
 'cat84',
 'cat85',
 'cat86',
 'cat87',
 'cat88',
 'cat89',
 'cat90',
 'cat91',
 'cat92',
 'cat93',
 'cat94',
 'cat95',
 'cat96',
 'cat97',
 'cat98',
 'cat99',
 'cat100',
 'cat101

In [82]:
train_x = train_copy[features]
train_y = train_copy['log_loss']
for c in range(len(cat_features)):
    train_x[cat_features[c]] = train_x[cat_features[c]].astype('category').cat.codes
print('Xtrain:',train_x.shape) # Xtrain: (188318, 130)
print('ytrain:',train_y.shape) # ytrain: (188318,)

Xtrain: (194592, 130)
ytrain: (194592,)


In [83]:
train_x

cat1  cat2  cat3  cat4  cat5  cat6  cat7  cat8  cat9  cat10  ...  \
0          0     1     0     1     0     0     0     0     1      0  ...   
1          0     1     0     0     0     0     0     0     1      1  ...   
2          0     1     0     0     1     0     0     0     1      1  ...   
3          1     1     0     1     0     0     0     0     1      0  ...   
4          0     1     0     1     0     0     0     0     1      1  ...   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...   
194587     0     1     0     0     0     0     0     0     1      0  ...   
194588     0     0     0     0     0     1     0     0     0      0  ...   
194589     0     1     0     0     0     0     0     1     1      0  ...   
194590     0     1     0     0     0     0     0     0     1      1  ...   
194591     1     0     0     1     0     0     0     0     0      0  ...   

           cont5     cont6     cont7    cont8    cont9   cont10    cont11  \
0       0.310061  0.718367  0.335060  0.30260  0.67135  0.83510  0.569745   
1       0.885834  0.438917  0.436585  0.60087  0.35127  0.43919  0.338312   
2       0.397069  0.289648  0.315545  0.27320  0.26076  0.32446  0.381398   
3       0.422268  0.440945  0.391128  0.31796  0.32128  0.44467  0.327915   
4       0.704268  0.178193  0.247408  0.24564  0.22089  0.21230  0.204687   
...          ...       ...       ...      ...      ...      ...       ...   
194587  0.939556  0.242437  0.289949  0.24564  0.30859  0.32935  0.223038   
194588  0.704268  0.334270  0.382000  0.63475  0.40455  0.47779  0.307628   
194589  0.482436  0.345883  0.370534  0.24564  0.45808  0.47779  0.445614   
194590  0.340543  0.704364  0.562866  0.34987  0.44767  0.53881  0.863052   
194591  0.281143  0.844563  0.533048  0.97123  0.93383  0.83814  0.932195   

          cont12    cont13    cont14  
0       0.594646  0.822493  0.714843  
1       0.366307  0.611431  0.304496  
2       0.373424  0.195709  0.774425  
3       0.321570  0.605077  0.602642  
4       0.202213  0.246011  0.432606  
...          ...       ...       ...  
194587  0.220003  0.333292  0.208216  
194588  0.301921  0.318646  0.305872  
194589  0.443374  0.339244  0.503888  
194590  0.852865  0.654753  0.721707  
194591  0.946432  0.810511  0.721460  

[194592 rows x 130 columns]

In [84]:
train_copy

id cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9  ...     cont7  \
0            1    A    B    A    B    A    A    A    A    B  ...  0.335060   
1            2    A    B    A    A    A    A    A    A    B  ...  0.436585   
2            5    A    B    A    A    B    A    A    A    B  ...  0.315545   
3           10    B    B    A    B    A    A    A    A    B  ...  0.391128   
4           11    A    B    A    B    A    A    A    A    B  ...  0.247408   
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...   
194587  587620    A    B    A    A    A    A    A    A    B  ...  0.289949   
194588  587624    A    A    A    A    A    B    A    A    A  ...  0.382000   
194589  587630    A    B    A    A    A    A    A    B    B  ...  0.370534   
194590  587632    A    B    A    A    A    A    A    A    B  ...  0.562866   
194591  587633    B    A    A    B    A    A    A    A    A  ...  0.533048   

          cont8    cont9   cont10    cont11    cont12    cont13    cont14  \
0       0.30260  0.67135  0.83510  0.569745  0.594646  0.822493  0.714843   
1       0.60087  0.35127  0.43919  0.338312  0.366307  0.611431  0.304496   
2       0.27320  0.26076  0.32446  0.381398  0.373424  0.195709  0.774425   
3       0.31796  0.32128  0.44467  0.327915  0.321570  0.605077  0.602642   
4       0.24564  0.22089  0.21230  0.204687  0.202213  0.246011  0.432606   
...         ...      ...      ...       ...       ...       ...       ...   
194587  0.24564  0.30859  0.32935  0.223038  0.220003  0.333292  0.208216   
194588  0.63475  0.40455  0.47779  0.307628  0.301921  0.318646  0.305872   
194589  0.24564  0.45808  0.47779  0.445614  0.443374  0.339244  0.503888   
194590  0.34987  0.44767  0.53881  0.863052  0.852865  0.654753  0.721707   
194591  0.97123  0.93383  0.83814  0.932195  0.946432  0.810511  0.721460   

           loss  log_loss  
0       2213.18  7.702186  
1       1283.60  7.157424  
2       3005.09  8.008063  
3        939.85  6.845720  
4       2763.85  7.924380  
...         ...       ...  
194587  1198.62  7.088926  
194588  1108.34  7.010619  
194589  5762.64  8.659151  
194590  1562.87  7.354279  
194591  4751.72  8.466262  

[194592 rows x 133 columns]

In [85]:
#评估策略，e的次幂，用来评估。
#结果衡量方法：使用平均绝对误差来衡量
#mean_absolute_error(np.exp(y), np.exp(yhat))。
#定义计算损失值的函数
def xg_eval_mae(yhat,dtrain):
    y = dtrain.get_label()
    return 'mae',mean_absolute_error(np.exp(y),np.exp(yhat))

In [87]:
#数据类型转换成库可以使用的底层格式。
dtrain = xgb.DMatrix(train_x,train_copy['log_loss'])
dtrain

In [88]:
xgb_params = {
    'seed': 0,
    'eta': 0.1,
    'colsample_bytree': 0.5,
    'silent': 1,
    'subsample': 0.5,
    'objective': 'reg:linear',
    'max_depth': 5,
    'min_child_weight': 3
}

In [90]:
%%time

#feval:评估策略
bst_cv1 = xgb.cv(xgb_params, dtrain, num_boost_round=50, nfold=3, seed=0, 
                feval=xg_eval_mae, maximize=False, early_stopping_rounds=10)

print ('CV score:', bst_cv1.iloc[-1,:]['test-mae-mean'])

[15:49:52] WARNING: c:\ci\xgboost-split_1619728435298\work\src\objective\regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[15:49:52] WARNING: ..\src\learner.cc:541: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[15:49:52] WARNING: c:\ci\xgboost-split_1619728435298\work\src\objective\regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[15:49:52] WARNING: ..\src\learner.cc:541: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[15:49:52] WARNING: c:\ci\xgboost-spli

In [92]:
plt.figure()
bst_cv1[['train-mae-mean', 'test-mae-mean']].plot() 
plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

In [93]:
import pickle
import xgboost as xgb

import numpy as np
from sklearn.model_selection import KFold, train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, mean_squared_error
from sklearn.datasets import load_iris, load_digits, load_boston

rng = np.random.RandomState(31337)

In [96]:
digits = load_digits(n_class=2)
y = digits['target']
X = digits['data']
kf = KFold(n_splits=2, shuffle=True, random_state=rng)
for train_index, test_index in kf.split(X):
    xgb_model = xgb.XGBClassifier(n_jobs=1).fit(X[train_index], y[train_index])
    predictions = xgb_model.predict(X[test_index])
    actuals = y[test_index]
    print(confusion_matrix(actuals, predictions))

[17:13:28] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[86  2]
 [ 3 89]]
[17:13:28] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[90  0]
 [ 0 90]]


In [95]:
iris = load_iris()
y = iris['target']
X = iris['data']
kf = KFold(n_splits=2, shuffle=True, random_state=rng)
for train_index, test_index in kf.split(X):
    xgb_model = xgb.XGBClassifier(n_jobs=1).fit(X[train_index], y[train_index])
    predictions = xgb_model.predict(X[test_index])
    actuals = y[test_index]
    print(confusion_matrix(actuals, predictions))

[17:11:47] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[19  0  0]
 [ 0 31  3]
 [ 0  1 21]]
[17:11:47] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[31  0  0]
 [ 0 16  0]
 [ 0  1 27]]


In [97]:
import shap

ModuleNotFoundError: No module named 'shap'